services:
  php:
    restart: on-failure
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - myNetwork

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - myNetwork
  
  mysql:
    image: mysql:latest      
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=php_blog
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    networks:
      - myNetwork


networks:
  myNetwork:
    driver: bridge