---
- name: Update apt packages
  apt:
    update_cache: yes
    
- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - software-properties-common
      - apt-transport-https
      - gnupg2
    state: present
    update_cache: yes

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  
- name: Add Docker repo to apt sources '/etc/apt/sources.list.d/docker.list'
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot

- name: Install Docker packages
  apt:
    name:
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Install docker-compose
  get_url: 
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: 'u+x,g+x'

- name: Set periodic docker prune
  cron:
    name: docker-prune
    job: 'docker system prune -f --filter "until=$((30*24))h"'
    minute: '0'
    hour: '1'

- name: Remove unnecessary packages & dependencies
  apt:
    autoclean: yes
    autoremove: yes