---
- name: Change permissions
  hosts: all
  become: yes
  become_user: deploy
  tasks:
  - name: Change /public/images directory permissions
    file:
      path: /home/deploy/app/public/images
      state: directory
      group: www-data
      mode: 'g+rws'
