---
- name: Git clone repo
  hosts: all
  become: true
  become_user: deploy
  tasks:
  - name: Check if Git is installed
    become: yes
    apt:
      name: git
      state: present

  - name: Create /app directory
    file:
      path: /home/deploy/app
      state: directory
      mode: '0755'

  - name: Clone PHP blog repo
    git:    
      accept_hostkey: yes
      repo: https://github.com/elbroandrew/php-blog
      dest: /home/deploy/app/
      clone: yes

  - name: Change 'public/images/' directory permissions
    file:
      path: /home/deploy/app/public/images
      state: directory
      group: www-data
      mode: 'g+rws'
      recurse: yes
