site:
	ansible-playbook -i hosts.yml site.yml -K -vv

authorize:
	ansible-playbook -i hosts.yml authorize.yml -K

clone:
	ansible-playbook -i hosts.yml clone_repo.yml -K

up:
	ansible-playbook -i hosts.yml up.yml -K

down:
		ansible-playbook -i hosts.yml down.yml -K