site:
	ansible-playbook -i hosts.yml site.yml -K -vv

authorize:
	ansible-playbook -i hosts.yml authorize.yml -K

clone:
	ansible-playbook -i hosts.yml clone_repo.yml -K -vvv

up:
	ansible-playbook -i hosts.yml up.yml -K

down:
	ansible-playbook -i hosts.yml down.yml -K

git-update:
	ansible-playbook -i hosts.yml update_repo.yml -K

perm-access:
	ansible-playbook -i hosts.yml change_perms.yml -K -vv